apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: hscript/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: hscript/roles
      context: roles
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: hscript/interviews
    #   context: interviews
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    - image: hscript/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    # - image: hscript/tickets
    #   context: tickets
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    # - image: hscript/orders
    #   context: orders
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    # - image: hscript/expiration
    #   context: expiration
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    # - image: hscript/payments
    #   context: payments
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
