apiVersion: apps/v1
kind: Deployment
metadata:
  name: interviews-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interviews
  template:
    metadata:
      labels:
        app: interviews
    spec:
      containers:
        - name: interviews
          image: hscript/interviews
          env:
            - name: MONGO_URI
              value: "mongodb://interviews-mongo-srv:27017/interviews"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: "https://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: organization
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: interviews-srv
spec:
  selector:
    app: interviews
  ports:
    - name: interviews
      protocol: TCP
      port: 3000
      targetPort: 3000
