apiVersion: apps/v1
kind: Deployment
metadata:
  name: roles-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roles
  template:
    metadata:
      labels:
        app: roles
    spec:
      containers:
        - name: roles
          image: hscript/roles
          env:
            - name: MONGO_URI
              value: "mongodb://roles-mongo-srv:27017/roles"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: roles-srv
spec:
  selector:
    app: roles
  ports:
    - name: roles
      protocol: TCP
      port: 3000
      targetPort: 3000
