name: tests-roles

on:
    pull_request:
        paths:
            - 'roles/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd roles && npm install && npm run test:ci
